### PR TITLE
8693qpawd: 8693qpatt: 8693qpaw5: Favorites page

### PR DESCRIPTION
**Pull request by kate-prakofyeva**
**Description**
Added favorites page, theme button style, favorites context

**Type of change**
- [x] Feature (introduces new functionality)
- [x] Styles

**PR Checklist**
- [x] Description of the changes has been added (Screenshots/Video)
- [x] Commit messages follow [conventional commits guideline](https://www.conventionalcommits.org/en/v1.0.0-beta.4/#summary)

image
image
image

https://github.com/PL-FE-SEP23-JANUSZ3X/product_catalog/assets/147045521/7abce041-f968-4264-a973-d602c0c6419c

### CODE REVIEW

**Review by Timi2424 — APPROVED** [review]
👍 THIS IS A LOT!

**Comment by kate-prakofyeva** [comment]
image

**Review by Timi2424 — APPROVED** [review]
👍 great!

**Review by Patrykmclaren14 — APPROVED** [review]
Good job!

**Pull request merged**
